/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "",
  "description": "学习创建个人博客",
  "base": "/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/favicon.ico"
      }
    ],
    [
      "meta",
      {
        "name": "author",
        "content": "朱金发"
      }
    ],
    [
      "meta",
      {
        "name": "vuepress",
        "content": "Hello Vuepress!"
      }
    ]
  ],
  "pages": [
    {
      "title": "分类",
      "frontmatter": {
        "sidebar": "auto"
      },
      "regularPath": "/111.html",
      "relativePath": "111.md",
      "key": "v-7c4f1237",
      "path": "/111.html",
      "headers": [
        {
          "level": 2,
          "title": "分类",
          "slug": "分类"
        },
        {
          "level": 2,
          "title": "二级标题",
          "slug": "二级标题"
        },
        {
          "level": 2,
          "title": "二级标题",
          "slug": "二级标题-2"
        },
        {
          "level": 2,
          "title": "二级标题",
          "slug": "二级标题-3"
        },
        {
          "level": 2,
          "title": "二级标题",
          "slug": "二级标题-4"
        }
      ]
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroText": null,
        "tagline": "Hero 副标题",
        "features": [
          {
            "title": "简洁至上",
            "details": "以 Markdown 为中心的项目结构，以最少的配置帮助你专注于写作。"
          },
          {
            "title": "Vue驱动",
            "details": "享受 Vue + webpack 的开发体验，在 Markdown 中使用 Vue 组件，同时可以使用 Vue 来开发自定义主题。"
          },
          {
            "title": "高性能",
            "details": "VuePress 为每个页面预渲染生成静态的 HTML，同时在页面被加载的时候，将作为 SPA 运行。"
          }
        ],
        "footer": "MIT Licensed | Copyright © 2018-present Evan You"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-06360df8",
      "path": "/"
    },
    {
      "title": "关于我",
      "frontmatter": {},
      "regularPath": "/about/",
      "relativePath": "about/README.md",
      "key": "v-3b04bbb5",
      "path": "/about/",
      "headers": [
        {
          "level": 2,
          "title": "关于我",
          "slug": "关于我"
        }
      ]
    },
    {
      "title": "分类",
      "frontmatter": {
        "sidebar": "auto"
      },
      "regularPath": "/category/",
      "relativePath": "category/README.md",
      "key": "v-6a6e11a7",
      "path": "/category/",
      "headers": [
        {
          "level": 2,
          "title": "分类",
          "slug": "分类"
        },
        {
          "level": 2,
          "title": "二级标题",
          "slug": "二级标题"
        },
        {
          "level": 2,
          "title": "二级标题",
          "slug": "二级标题-2"
        },
        {
          "level": 2,
          "title": "二级标题",
          "slug": "二级标题-3"
        },
        {
          "level": 2,
          "title": "二级标题",
          "slug": "二级标题-4"
        }
      ]
    }
  ],
  "themeConfig": {
    "lastUpdated": "Last Updated",
    "logo": "/assets/img/github.png",
    "nav": [
      {
        "text": "首页",
        "link": "/"
      },
      {
        "text": "分类",
        "link": "/category/"
      },
      {
        "text": "关于我",
        "link": "/about/"
      }
    ],
    "sidebar": [
      "/",
      "/about",
      [
        "/category"
      ]
    ]
  }
}